module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testMatch: ["**/test/**/*.test.ts"],
  collectCoverageFrom: ["src/**/*.ts"],
  coveragePathIgnorePatterns: [
    "src/.*\\.test\\.ts$",
    "src/.*\\.spec\\.ts$",
    "test/.*",
    "generated/.*",
    ".*/generated/.*",
    "node_modules/.*",
    ".*\\.d\\.ts$",
    "src/Constants\\.ts$",
    "src/CustomTypes\\.ts$",
    "src/Pools/common\\.ts$",
  ],
  coverageReporters: ["text", "text-summary"],
  testTimeout: 120000,
};
